version: '3.5'
services: 
    worker:
        build:
            context: .
            dockerfile: ./dockerfiles/Dockerfile
        command: python -m celery -A runner worker -l info
        restart: unless-stopped
        working_dir: /app
        volumes:
        - ./app:/app
        - /var/run/docker.sock:/var/run/docker.sock
        - ai-images:/tmp

    beat:
        build:
            context: .
            dockerfile: ./dockerfiles/Dockerfile
        command: python -m celery -A runner beat -l info
        restart: unless-stopped
        working_dir: /app
        volumes:
        - ./app:/app
        - ai-images:/tmp
        - /var/run/docker.sock:/var/run/docker.sock

    orthanc:
        image: jodogne/orthanc-plugins:1.7.1
        command: /run/secrets/  # Path to the configuration files (stored as secrets)
        restart: unless-stopped
        volumes:
        - orthanc-volume:/var/lib/orthanc/db
        ports:
        - 4243:4242
        - 8043:8042
        secrets:
        - orthanc.json

networks:
    default:
        external:
            name: ai-network

volumes:
    orthanc-volume:
        name: orthanc-volume
    ai-images:
        name: ai-images

secrets:
    orthanc.json:
        file: ./orthanc.json