version: '3.5'
services: 
    worker:
        build:
            context: .
            dockerfile: ./dockerfiles/Dockerfile
        command: celery -A runner worker -l info
        restart: on-failure
        working_dir: /app
        volumes:
        - ./app:/app
        - /var/run/docker.sock:/var/run/docker.sock
        privileged: true

    orthanc:
        image: jodogne/orthanc-plugins:1.7.1
        command: /run/secrets/  # Path to the configuration files (stored as secrets)
        ports:
        - 4242:4242
        - 8042:8042
        secrets:
        - orthanc.json

networks:
    default:
        external:
            name: ai-network


secrets:
    orthanc.json:
        file: ./orthanc.json