version: '2.3'
services: 
    worker_gpu:
        build:
            context: .
            dockerfile: ./dockerfiles/Dockerfile
        command: python -m celery -A runner worker -E -Q celery -c 1
        restart: unless-stopped

        working_dir: /app
        volumes:
        - ./app:/app
        - /var/run/docker.sock:/var/run/docker.sock
        - ai-images:/opt/images
    worker:
        build:
            context: .
            dockerfile: ./dockerfiles/Dockerfile
        command: python -m celery -A runner worker  -E -Q no_gpu
        restart: unless-stopped
        working_dir: /app
        volumes:
        - ./app:/app
        - /var/run/docker.sock:/var/run/docker.sock
        - ai-images:/opt/images
    results:
        build:
            context: .
            dockerfile: ./dockerfiles/Dockerfile
        command: python results_processor.py
        restart: unless-stopped
        working_dir: /app
        volumes:
        - ./app:/app
        - /var/run/docker.sock:/var/run/docker.sock
        - ai-images:/opt/images

    beat:
        build:
            context: .
            dockerfile: ./dockerfiles/Dockerfile
        command: python -m celery -A runner beat 
        restart: unless-stopped
        working_dir: /app
        volumes:
        - ./app:/app
        - ai-images:/opt/images
        - /var/run/docker.sock:/var/run/docker.sock

    orthanc:
        build:
            context: .
            dockerfile: dockerfiles/orthanc.Dockerfile
        restart: unless-stopped
        volumes: ["orthanc-storage:/var/lib/orthanc/db"]
        expose:
        - 8042
        - 4242
    orthanc-public:
        build:
            context: .
            dockerfile: dockerfiles/orthanc.public.Dockerfile
        restart: unless-stopped
        volumes: ["orthanc-storage:/var/lib/orthanc/db"]
        ports:
        - 4243:4242
        - 8043:8042

networks:
    default:
        external:
            name: ai-network


volumes:
    ai-images:
        external:
            name: ai-images
    orthanc-storage:
        external:
            name: orthanc-storage
# volumes:
#     orthanc-volume:
#         name: orthanc-volume
#     ai-images:
#         name: ai-images