version: '2.3'
services: 
    worker:
        build:
            context: .
            dockerfile: ./dockerfiles/Dockerfile
        command: python -m celery -A runner worker -l info
        restart: unless-stopped
        working_dir: /app
        volumes:
        - ./app:/app
        - /var/run/docker.sock:/var/run/docker.sock
        - ai-images:/tmp

    beat:
        build:
            context: .
            dockerfile: ./dockerfiles/Dockerfile
        command: python -m celery -A runner beat -l info
        restart: unless-stopped
        working_dir: /app
        volumes:
        - ./app:/app
        - ai-images:/tmp
        - /var/run/docker.sock:/var/run/docker.sock

    orthanc:
        build:
            context: .
            dockerfile: dockerfiles/orthanc.Dockerfile
        image: jodogne/orthanc-plugins:1.7.1
        restart: unless-stopped
        volumes: ["orthanc-storage:/var/lib/orthanc/db:Z"]
        ports:
        - 4243:4242
        - 8042:8042

networks:
    default:
        external:
            name: ai-network


volumes:
    ai-images:
        external:
            name: ai-images
    orthanc-storage:
        external:
            name: orthanc-storage
# volumes:
#     orthanc-volume:
#         name: orthanc-volume
#     ai-images:
#         name: ai-images