version: '3.3'
services: 
    worker:
        build:
            context: .
            dockerfile: ./dockerfiles/Dockerfile
        command: celery -A runner worker -l info
        depends_on:
        - redis
        - rabbitmq
        restart: on-failure
        working_dir: /app
        volumes:
        - ./app:/app
        - /var/run/docker.sock:/var/run/docker.sock
        privileged: true

    # beat:
    #     build:
    #         context: .
    #         dockerfile: ./dockerfiles/Dockerfile
    #     command: celery -A runner beat -l info
    #     depends_on:
    #     - rabbitmq
    #     restart: 'no'
    #     working_dir: /app
    #     volumes:
    #     - ./app:/app
    #     - /var/run/docker.sock:/var/run/docker.sock
    #     privileged: true

    rabbitmq:
        image: rabbitmq:3.7.8
        ports:
        - 5672:5672

    redis:
        image: redis
        ports:
        - 6379:6379

    orthanc:
        image: jodogne/orthanc-plugins:1.7.1
        command: /run/secrets/  # Path to the configuration files (stored as secrets)
        ports:
        - 4242:4242
        - 8042:8042
        secrets:
        - orthanc.json

secrets:
    orthanc.json:
        file: orthanc.json